### PR TITLE
CustomerController finished with Put and Delete

### LINKED ISSUE #1: Allow developers to access Customer resource
Verbs to be supported

1. GET
1. POST
1. PUT

User should be able to GET a list of customers, and GET a single customer.

### PR DESCRIPTION
**Pull request by therealrmac**
Fixes #1 . 

Changes proposed in this pull request: 
- Added functionality for the Customers Put and Delete (even though we don't need the delete apparently)
-
-

How to test: 
- Pull down my branch 
- run your server/open it in Postman make a customer and then make a change in PUT
- Use delete to remove the customer. (if you want)

@EnRonSwanson/

### CODE REVIEW

**Comment by adamreidelbach** [comment]
👍

**Comment by madelineepower** [comment]
👍 PUT looks good on my Postman 🥇

**Review by adamreidelbach — COMMENTED** [review]
👍

**Comment by mitchellblom** [comment]
👍

**Pull request merged**
