### PR TITLE
Adam

### LINKED ISSUE #5: Allow developers to access the Product Type resource
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by adamreidelbach**
Fixes #5  and #7 .

Changes proposed in this pull request: 
- Added Get (all and single), Post, Put, Delete functionality to ProductType Controller
- Added Get (all and single), Post, Put functionality to Department Controller

How to test: 
- Run all calls in postman or terminal and confirm changes in browser / db

@EnRonSwanson/

### CODE REVIEW

**Comment by therealrmac** [comment]
Department controller works

**Comment by therealrmac** [comment]
ProductType controller works too

**Comment by madelineepower** [comment]
👍 tested in postman and browser

**Comment by mitchellblom** [comment]
👍 all works

**Pull request merged**
