### PR TITLE
Employee Controller and Order controller completed some values can be…

### LINKED ISSUE #4: Allow developers to access the Order resource
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by therealrmac**
… null but that was to make it work

Fixes #4  #6 .

Changes proposed in this pull request: 
- I made small changes to the Foreign Keys on Employee and Order controllers
- Both of these controllers should function correctly
-

How to test: 
- Order: provide a customerId in postman to create an order and the rest will take care of itself/the paymentTypeId will be needed later too but for now you don't need it - MAKE SURE YOU HAVE A CUSTOMER CREATED FIRST OTHERWISE IT WILL NOT WORK
- Employee: Provide a full name, a value for supervisor (1 or 0), and the rest will be taken care of/ the departmentId will be required later but for now you don't need it.
-

@EnRonSwanson/

### CODE REVIEW

**Review by adamreidelbach — COMMENTED** [review]
👍 Tested calls using Postman and the browser

**Comment by madelineepower** [comment]
👍 works looks great tested and done

**Comment by mitchellblom** [comment]
👍 tested it earlier and now. all good.

**Comment by therealrmac** [comment]
html r00lz dood

**Pull request merged**
