### PR TITLE
ordercontroller posting product to new order

### LINKED ISSUE #10: Order detail JSON should contain product details
Update the Order detail JSON object should contain all nested Product information.

For example:

```js
{
   OrderId: 21,
   CustomerId: 16,
   PaymentTypeId: 83,
   Products: [
      {
         ProductId: 156,
         Name: "Kite",
         Price: 14.25
         Quantity: 1
      },
      {
         ProductId: 212,
         Name: "Roller blades",
         Price: 88.99
         Quantity: 1
      }
   ]
}
```

### PR DESCRIPTION
**Pull request by madelineepower**
Fixes #10 .

Changes proposed in this pull request: 
- OrderController is posting an existing product to the orderProduct table and creating a new order
- dotnet watch
- code to prevent the loop

How to test: 
- Pass an entire Product object into the Order controllers Post
- Change "sellerId" to "buyerId"

@EnRonSwanson/

### CODE REVIEW

**Comment by therealrmac** [comment]
👍

**Comment by therealrmac** [comment]
Works fine 👍

**Comment by therealrmac** [comment]
We'll get the put to work tomorrow though.

**Comment by adamreidelbach** [comment]
👍

**Pull request merged**
