### PR TITLE
get and post for customer

### PR DESCRIPTION
**Pull request by mitchellblom**
Fixes # - corrected customer model to post and get properly

Changes proposed in this pull request: 
- Took out required fields for account creation date and activity
- Created constructor for DateTime of account creation
- Edited active status to be prepopulated with 1 instead of a boolean

How to test: 
- Postman or browser

@EnRonSwanson/

### CODE REVIEW

**Comment by madelineepower** [comment]
👍

**Comment by mitchellblom** [comment]
Now also addressing Fix #1. Post & Get on Customer working and tested in postman and browser.

**Comment by therealrmac** [comment]
Get and Post work fine

**Comment by madelineepower** [comment]
👍 Get and post working on my machine

**Comment by adamreidelbach** [comment]
👍

**Pull request merged**
