### PR TITLE
Mitchell

### LINKED ISSUE #8: Allow developers to access the Computer resource
Verbs to be supported

1. GET
1. POST
1. PUT
1. DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by mitchellblom**
Fixes #8 and #9 .

Changes proposed in this pull request:

- Added Get (all and single), Post, Put, Delete functionality to Computer Controller
- Added Get (all and single), Post, Put functionality to TrainingProgram Controller

How to test:
Run all calls in postman or terminal and confirm changes are identical in browser / db

@EnRonSwanson/

### CODE REVIEW

**Comment by adamreidelbach** [comment]
👍  Tested all calls with Postman and the browser

**Comment by therealrmac** [comment]
Computer controller works

**Comment by therealrmac** [comment]
TrainingProgram controller works

**Comment by madelineepower** [comment]
👍 TESTED ON POSTMAN AND BROWSER - ALL CALLS LOOK GOOD

**Pull request merged**
